import React, { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { motion } from 'framer-motion'
import { useForm } from 'react-hook-form'
import { FaArrowRight, FaBars, FaCheck, FaChevronUp, FaFacebookF, FaHardHat, FaLinkedinIn, FaPhoneAlt, FaQuoteLeft, FaShieldAlt, FaTimes, FaWhatsapp } from 'react-icons/fa'
import { FiActivity, FiBriefcase, FiCpu, FiDroplet, FiLayers, FiSettings, FiTool, FiUsers } from 'react-icons/fi'
import './styles.css'

const services = [
  ['Mechanical Engineering', 'Reliable design, repair and mechanical support for industrial operations.', FiSettings],
  ['Structural Steel Fabrication', 'Precision-crafted steelwork tailored to your site and specifications.', FiLayers],
  ['Plant Maintenance', 'Planned maintenance that keeps critical assets running efficiently.', FiTool],
  ['Welding Services', 'Qualified welding solutions for fabrication, repair and installation.', FiActivity],
  ['Industrial Installations', 'Safe, coordinated installation of industrial systems and equipment.', FiCpu],
  ['Engineering Consulting', 'Practical technical guidance that moves projects forward with confidence.', FiBriefcase],
]
const industries = [['Mining', FaHardHat], ['Manufacturing', FiSettings], ['Construction', FiLayers], ['Industrial Plants', FiCpu], ['Agriculture', FiActivity], ['Energy', FiDroplet], ['Water Treatment', FiDroplet], ['Municipal Infrastructure', FiUsers]]
const projects = [
  ['Plant Reliability Upgrade', 'Mechanical refurbishment and preventative-maintenance programme.', 'Industrial client', 'KwaZulu-Natal', '2025', 'project-one'],
  ['Structural Steel Works', 'Fabrication and installation of a purpose-built steel structure.', 'Construction client', 'Durban', '2024', 'project-two'],
  ['Process Pipe Fabrication', 'Workshop and on-site pipe fabrication for a processing facility.', 'Manufacturing client', 'Gauteng', '2024', 'project-three'],
]
const fade = { hidden: { opacity: 0, y: 22 }, show: { opacity: 1, y: 0 } }
function SectionTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="section-title"><span>{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</div> }
function App() {
  const [menu, setMenu] = useState(false); const [top, setTop] = useState(false)
  React.useEffect(() => { const fn=()=>setTop(window.scrollY>500); window.addEventListener('scroll',fn); return ()=>window.removeEventListener('scroll',fn) }, [])
  const { register, handleSubmit, reset, formState: { errors } } = useForm(); const [sent,setSent] = useState(false)
  const nav = ['Home','About','Services','Projects','Industries','Contact']
  return <><header><a className="brand" href="#home" aria-label="Ensimbini Engineering home"><b>EN</b><span>ENSIMBINI<small>ENGINEERING C.C.</small></span></a><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">{menu?<FaTimes/>:<FaBars/>}</button><nav className={menu?'open':''}>{nav.map(n=><a onClick={()=>setMenu(false)} href={'#'+n.toLowerCase()} key={n}>{n}</a>)}<a className="nav-cta" href="#contact">Request a quote</a></nav></header>
  <main>
    <section className="hero" id="home"><div className="hero-shade"/><div className="container hero-content"><motion.p initial="hidden" animate="show" variants={fade} className="eyebrow">ENGINEERING SOLUTIONS FOR SOUTH AFRICA</motion.p><motion.h1 initial="hidden" animate="show" transition={{delay:.12}} variants={fade}>Engineering excellence built on <em>quality, innovation</em> &amp; trust.</motion.h1><motion.p initial="hidden" animate="show" transition={{delay:.22}} variants={fade} className="lead">Professional engineering, fabrication, maintenance, installation and technical solutions for the industries that keep South Africa moving.</motion.p><motion.div initial="hidden" animate="show" transition={{delay:.32}} variants={fade} className="actions"><a className="button orange" href="#contact">Request a quote <FaArrowRight/></a><a className="button ghost" href="#services">Explore services</a></motion.div></div><div className="hero-stat"><strong>Built for performance.</strong><span>Committed to doing the job right.</span></div></section>
    <section className="intro section" id="about"><div className="container split"><div><SectionTitle eyebrow="WHO WE ARE" title="Engineered to deliver, built to last."/><p>Ensimbini Engineering C.C. is an engineering partner focused on practical, high-quality solutions. From fabrication and installations to maintenance and repairs, we bring disciplined workmanship to every project.</p><p>We are committed to safe execution, clear communication and outcomes our clients can rely on.</p><a className="text-link" href="#contact">Talk to our team <FaArrowRight/></a></div><div className="principles"><div><FaCheck/><span><b>Mission</b>Deliver dependable engineering solutions with integrity and precision.</span></div><div><FaCheck/><span><b>Vision</b>Be the trusted name behind high-performing industrial operations.</span></div><div><FaCheck/><span><b>Values</b>Quality workmanship, safety, reliability and customer satisfaction.</span></div></div></div></section>
    <section className="section soft" id="services"><div className="container"><SectionTitle eyebrow="OUR CAPABILITIES" title="Solutions for every stage of your operation." text="Skilled people, practical thinking and the right standards for demanding environments."/><div className="card-grid services">{services.map(([name,desc,Icon],i)=>{const I=Icon as any;return <motion.article viewport={{once:true}} whileInView="show" initial="hidden" transition={{delay:i*.05}} variants={fade} className="service-card" key={name as string}><I/><h3>{name as string}</h3><p>{desc as string}</p><a href="#contact" aria-label={`Ask about ${name}`}>Learn more <FaArrowRight/></a></motion.article>})}</div></div></section>
    <section className="section" id="projects"><div className="container"><SectionTitle eyebrow="SELECTED WORK" title="Proven capability in the field."/><div className="projects">{projects.map(([title,desc,client,place,year,cls])=><article className="project" key={title}><div className={'project-image '+cls}><span>PROJECT</span></div><div className="project-body"><h3>{title}</h3><p>{desc}</p><dl><div><dt>Client</dt><dd>{client}</dd></div><div><dt>Location</dt><dd>{place}</dd></div><div><dt>Completed</dt><dd>{year}</dd></div></dl></div></article>)}</div></div></section>
    <section className="dark-band" id="industries"><div className="container"><SectionTitle eyebrow="INDUSTRIES WE SERVE" title="Experience where it counts."/><div className="industry-grid">{industries.map(([name,Icon])=>{const I=Icon as any;return <div key={name as string}><I/><span>{name as string}</span></div>})}</div></div></section>
    <section className="section"><div className="container"><SectionTitle eyebrow="WHY ENSIMBINI" title="A partner you can depend on."/><div className="why-grid">{[['Experienced engineers','Hands-on expertise for practical, precise outcomes.'],['High safety standards','Safety embedded in every phase of delivery.'],['Reliable delivery','Clear planning and dependable execution.'],['Competitive pricing','Value-led scope without compromising quality.'],['Certified quality','Workmanship focused on lasting performance.'],['Customer focus','Responsive collaboration from brief to completion.']].map(([t,d])=><div><FaShieldAlt/><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
    <section className="testimonials section soft"><div className="container"><SectionTitle eyebrow="CLIENT VOICES" title="Relationships built on results."/><div className="quote-grid">{[['“Ensimbini approached a challenging shutdown with excellent planning and a real commitment to safety.”','Operations Manager','Industrial client'],['“Their team was professional, responsive and delivered quality fabrication on schedule.”','Project Manager','Construction client'],['“We value their practical advice and dependable maintenance support.”','Maintenance Lead','Manufacturing client']].map(([q,n,r])=><blockquote><FaQuoteLeft/><p>{q}</p><footer><b>{n}</b><span>{r}</span></footer></blockquote>)}</div></div></section>
    <section className="cta"><div className="container"><div><span className="eyebrow">READY TO START?</span><h2>Let’s build a better solution.</h2></div><a className="button orange" href="#contact">Request a quote <FaArrowRight/></a></div></section>
    <section className="section contact" id="contact"><div className="container split"><div><SectionTitle eyebrow="CONTACT US" title="Tell us about your project." text="We’ll get back to you with the right next step."/><div className="contact-lines"><p><FaPhoneAlt/><span>Phone<small>+27 (0)00 000 0000</small></span></p><p><FiBriefcase/><span>Email<small>info@ensimbiniengineering.co.za</small></span></p><p><FiLayers/><span>Office<small>Durban, KwaZulu-Natal, South Africa</small></span></p></div><div className="map">Google Map<br/><small>Location placeholder</small></div></div><form onSubmit={handleSubmit(()=>{setSent(true);reset()})}><label>Name<input {...register('name',{required:true})} placeholder="Your name"/>{errors.name&&<small>Please enter your name.</small>}</label><label>Company<input {...register('company')} placeholder="Company name"/></label><label>Email<input type="email" {...register('email',{required:true})} placeholder="you@company.co.za"/>{errors.email&&<small>Please enter your email.</small>}</label><label>Phone<input {...register('phone')} placeholder="+27"/></label><label>Message<textarea {...register('message',{required:true})} rows={5} placeholder="How can we help?"/>{errors.message&&<small>Please add a message.</small>}</label><button className="button orange" type="submit">Send enquiry <FaArrowRight/></button>{sent&&<p className="success">Thank you — your enquiry is ready to be sent.</p>}</form></div></section>
  </main><footer className="footer"><div className="container footer-grid"><div><a className="brand" href="#home"><b>EN</b><span>ENSIMBINI<small>ENGINEERING C.C.</small></span></a><p>Professional engineering solutions, delivered with pride.</p></div><div><h4>Quick links</h4>{nav.slice(0,5).map(n=><a href={'#'+n.toLowerCase()}>{n}</a>)}</div><div><h4>Services</h4><a href="#services">Engineering</a><a href="#services">Fabrication</a><a href="#services">Maintenance</a><a href="#services">Installations</a></div><div><h4>Connect</h4><p>Durban, South Africa<br/>+27 (0)00 000 0000</p><div className="socials"><a href="#"><FaLinkedinIn/></a><a href="#"><FaFacebookF/></a></div></div></div><div className="copyright">© 2026 Ensimbini Engineering C.C. All Rights Reserved.</div></footer><a className="whatsapp" href="https://wa.me/27000000000" aria-label="Contact us on WhatsApp"><FaWhatsapp/></a>{top&&<button className="to-top" onClick={()=>scrollTo({top:0,behavior:'smooth'})} aria-label="Back to top"><FaChevronUp/></button>}</>
}
createRoot(document.getElementById('root')!).render(<App />)
